---
cloud_service_group: Database
cloud_service_type: CloudDB
name: Total Storage Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.cloud_db_server_instance_list.data_storage_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB