---
cloud_service_group: Compute
cloud_service_type: Server
name: Count By Instance Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.compute.instance_type
        fields:
          - name: value
            operator: count
options:
  chart_type: TREEMAP