---
cloud_service_group: Compute
cloud_service_type: Server
name: Total vCPU Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.hardware.cpu_count
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0