---
cloud_service_group: Compute
cloud_service_type: Server
name: Total Disk Size
query:
  aggregate:
    - unwind:
        path: data.storage
    - group:
        fields:
          - name: value
            key: data.storage.storage_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      source_unit: BYTES
      default: 0